Marginal gains in send/recv fast-path
faasm/faabric pull request #104
Opened 2021-06-07 15:22 UTC by csegarragonz

2021-06-07 15:55 UTC, csegarragonz commented on src/scheduler/MpiWorld.cpp
> -void MpiWorld::checkRankOnThisHost(int rank)
Even if we decide to keep the `if` statements, we can delete this method and keep the check in `getLocalQueue` through `getHostForRank`.

2021-06-08 07:09 UTC, csegarragonz commented on include/faabric/scheduler/MpiWorld.h
> +    std::vector<std::string> rankHostMap;
I could use `std::array` instad of `std::vector`, but the changes would then be more involved, as I would have to change the way we initialise the `MpiWorld` (arrays need to know their size at compile time).

2021-06-08 07:20 UTC, csegarragonz commented on tests/test/scheduler/test_mpi_world.cpp
> +    /*
By switching to `assert`-based errors, some tests that rely on `REQUIRE_THROWS` are not passing. I leave them commented here to remember to discuss about this. 

I've done some reading and it seems as though we could do [some dirty hacks](https://stackoverflow.com/a/38551114/10662021) to have assertions fails throw exceptions during testing, but not convinced.

2021-06-08 08:02 UTC, Shillaker requested changes

2021-06-08 08:02 UTC, Shillaker commented on include/faabric/scheduler/MpiWorld.h
> +    int getKeyForRanks(int sendRank, int recvRank);
Using the word "key" is a little confusing as it's not a map any more. Perhaps `getArrayIndexForRanks` or something.

This should also be `private` as it's an internal method. At the moment everything on this class is `public` which should be fixed as well (but in another PR).

2021-06-08 11:32 UTC, Shillaker approved these changes

2021-06-08 11:38 UTC, merged