Fix `Too many open files` problem in ZeroMQ
faasm/faabric pull request #264
Opened 2022-05-13 10:47 UTC by csegarragonz

2022-05-13 10:57 UTC, csegarragonz commented on tests/dist/mpi/test_mpi_functions.cpp
> +TEST_CASE_METHOD(MpiDistTestsFixture, "Test MPI all to all many times", "[mpi]")
This distributed test fails in the current `main` branch.

2022-05-20 15:32 UTC, csegarragonz commented on src/scheduler/MpiWorld.cpp
> +            if (m.dsthost() == thisHost && m.msg().mpirank() < localLeader) {
We used to call `initLocalRemote()` here, unfortunately that method is too coarse and was clearing the `rankForHost` structure before filling it again.

This was causing a race condition between migrated and non-migrated ranks.

2022-05-20 16:02 UTC, csegarragonz commented on src/scheduler/ExecGraph.cpp
> +void getMigratedMpiRankHostsFromExecGraph(const ExecGraph& graph,
Moved this method here so I can use it for Faasm tests as well.

2022-05-23 08:23 UTC, Shillaker requested changes

2022-05-23 08:23 UTC, Shillaker commented on src/scheduler/ExecGraph.cpp
> +        if (returnValue == 0) {
There's 26 lines and up to 3 levels of nesting in this code block, but no linebreaks. A bit of whitespace would make it easier to parse.

2022-05-23 08:23 UTC, Shillaker commented on include/faabric/scheduler/ExecGraph.h
> +                                          std::vector<std::string>& hostsAfter);
Passing vectors to be filled is a slightly unintuitive interface for a `getXYZ` method. If you're populating a vector you could call it `populateXYZ` or `appendXYZ`, but instead this should really return the two lists. Returning a `std::pair` of vectors seems more intuitive.

2022-05-23 08:23 UTC, Shillaker commented on src/scheduler/MpiWorld.cpp
> +            // the `UNDERFULL` topology hint. In general however, we don't
We don't use markup syntax in inline comments like this as it'll never be rendered as markup.

2022-05-23 08:23 UTC, Shillaker commented on src/scheduler/MpiWorld.cpp
> +            }
It's not enforced in the style guide but after a stand-alone `if` I'd expect a linebreak.

2022-05-23 08:23 UTC, Shillaker commented on tests/dist/mpi/test_mpi_functions.cpp
> +        SLEEP_MS(500);
Why does this need to sleep? As it's running 50 times and sleeping for half a second each time it's adding 25s of sleeping to the test run.

2022-05-23 08:23 UTC, Shillaker commented on tests/dist/mpi/test_mpi_functions.cpp
> +        SPDLOG_INFO("Starting run {}/{}", i + 1, numRuns);
I'm not sure this needs to be `INFO`, probably `DEBUG`.

2022-05-24 07:36 UTC, Shillaker requested changes
More linebreaks.

2022-05-24 07:36 UTC, Shillaker commented on src/scheduler/MpiWorld.cpp
> +            }
Linebreak following an if

2022-05-24 07:36 UTC, Shillaker commented on src/scheduler/MpiWorld.cpp
> +            // Update the ranks for host. This structure is used when doing
Linebreak preceding a comment.

2022-05-24 07:36 UTC, Shillaker commented on src/scheduler/MpiWorld.cpp
> +            // Update the host for this rank. We only update the positions of
Linebreak preceding a comment.

2022-05-24 07:36 UTC, Shillaker commented on src/scheduler/MpiWorld.cpp
> +            // To run migration experiments easily, we may want to propagate
Linebreak preceding a comment.

2022-05-24 07:36 UTC, Shillaker commented on src/scheduler/ExecGraph.cpp
> +            }
Linebreak following an if

2022-05-24 07:36 UTC, Shillaker commented on src/scheduler/MpiWorld.cpp
> +            }
Linebreak following an if/ preceding a comment.

2022-05-24 07:36 UTC, Shillaker commented on src/scheduler/MpiWorld.cpp
> +            if (ranksForHost[m.srchost()].empty()) {
Linebreak preceding this if as it's following a hard-to-read one-liner

2022-05-25 17:16 UTC, merged